### ISSUE TITLE
LICENSE is missing data and copyright holder

### ISSUE THREAD

**Issue by stephenpaulger** [ARM-software/CMSIS-CV#2]
LICENSE file doesn't have a date or copyright holder, just the placeholders.

**Comment by christophe0606** [comment]
@stephenpaulger It is normal. The LICENSE file is just describing the kind of LICENSE that is used (Apache).

Then each C, CPP source file or header has its own dedicated LICENSE and Copyright section.

It is what we do on other CMSIS projects.
